import time
import torch

#Hardware
CPUS = 20
GPUS = 2

#Program
NUM_COMPETITORS = 1
NUM_ITERS = 100000
NUM_EPS = 1000
VOCAB_WIDTH = 2
VOCAB_HEIGHT = 2
PROGRAM_WIDTH = 14
PROGRAM_HEIGHT = 14
PROGRAM_SIZE = 14
PREDICTION_LEN = (PROGRAM_WIDTH * PROGRAM_HEIGHT)  // (VOCAB_WIDTH * VOCAB_HEIGHT)
VOCAB_LEN = 2**(VOCAB_WIDTH*VOCAB_HEIGHT)
VOCAB = list(range(0, VOCAB_LEN))

# Simulations 
TEMP_THRESHOLD = 25
UPDATE_THRESHOLD = 0.6
MAX_LEN_OF_QUEUE = 20
NUM_MCTS_SIMS = 16
ARENA_COMPARE = 40
CPUCT = 1
EPS = 1e-8
ALPHA = 0.3
DIRICHLET_NOISE = True
NUM_ITERS_FOR_TRAIN_EXAMPLES_HISTORY = 20
    
# Game
GAME_STEPS = 100
GAME_HEIGHT = 114
GAME_WIDTH = 114
    
# Model
LR = 0.001
DROPOUT = 0.3
EPOCHS = 20
BATCH_SIZE = 1000
CUDA = torch.cuda.is_available()
RESNET_BLOCKS = 10
RESNET_INPUT_DEPTH = NUM_COMPETITORS + 1
RESNET_CHANNEL_DEPTH = 64
CHECKPOINT = './checkpoint/'
LOAD_MODEL = False
    
# Save and Load
SAVE_PROGRAMS = True
SAVE_PROGRAMS_INTERVAL = 5
TIME = str(int(time.time()))
OUTPUT_DIR = "./output/"
PROGRAM_DIR = ""
LOAD_FOLDER_FILE = ['./checkpoint/', 'checkpoint_4.pth.tar']
