# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.p1_path = QtWidgets.QLineEdit(self.frame)
        self.p1_path.setReadOnly(True)
        self.p1_path.setObjectName("p1_path")
        self.horizontalLayout_2.addWidget(self.p1_path)
        self.p1_open = QtWidgets.QToolButton(self.frame)
        self.p1_open.setObjectName("p1_open")
        self.horizontalLayout_2.addWidget(self.p1_open)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.p2_path = QtWidgets.QLineEdit(self.frame_2)
        self.p2_path.setReadOnly(True)
        self.p2_path.setObjectName("p2_path")
        self.horizontalLayout_3.addWidget(self.p2_path)
        self.p2_open = QtWidgets.QToolButton(self.frame_2)
        self.p2_open.setObjectName("p2_open")
        self.horizontalLayout_3.addWidget(self.p2_open)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.percent_bar = QtWidgets.QLabel(self.widget)
        self.percent_bar.setText("")
        self.percent_bar.setObjectName("percent_bar")
        self.verticalLayout.addWidget(self.percent_bar)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.frame_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_4 = QtWidgets.QWidget(self.splitter)
        self.widget_4.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.path1_tree = QtWidgets.QTreeView(self.widget_4)
        self.path1_tree.setObjectName("path1_tree")
        self.verticalLayout_2.addWidget(self.path1_tree)
        self.path2_tree = QtWidgets.QTreeView(self.widget_4)
        self.path2_tree.setObjectName("path2_tree")
        self.verticalLayout_2.addWidget(self.path2_tree)
        self.arena = QtWidgets.QWidget(self.splitter)
        self.arena.setObjectName("arena")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.arena)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.arena)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.play_button = QtWidgets.QToolButton(self.widget_3)
        self.play_button.setObjectName("play_button")
        self.gridLayout.addWidget(self.play_button, 0, 0, 1, 1)
        self.step_button = QtWidgets.QToolButton(self.widget_3)
        self.step_button.setObjectName("step_button")
        self.gridLayout.addWidget(self.step_button, 1, 0, 1, 1)
        self.reset_button = QtWidgets.QToolButton(self.widget_3)
        self.reset_button.setObjectName("reset_button")
        self.gridLayout.addWidget(self.reset_button, 4, 0, 1, 1)
        self.multistep_button = QtWidgets.QToolButton(self.widget_3)
        self.multistep_button.setEnabled(True)
        self.multistep_button.setObjectName("multistep_button")
        self.gridLayout.addWidget(self.multistep_button, 2, 0, 1, 1)
        self.pause_button = QtWidgets.QToolButton(self.widget_3)
        self.pause_button.setObjectName("pause_button")
        self.gridLayout.addWidget(self.pause_button, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.canvas_label = QtWidgets.QLabel(self.arena)
        self.canvas_label.setEnabled(True)
        self.canvas_label.setObjectName("canvas_label")
        self.horizontalLayout_5.addWidget(self.canvas_label)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mistake = QtWidgets.QAction(MainWindow)
        self.mistake.setObjectName("mistake")
        self.menuFile.addAction(self.mistake)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.p1_open.setText(_translate("MainWindow", "..."))
        self.p2_open.setText(_translate("MainWindow", "..."))
        self.play_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Run</p></body></html>"))
        self.play_button.setText(_translate("MainWindow", "..."))
        self.step_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Single step</p></body></html>"))
        self.step_button.setText(_translate("MainWindow", "..."))
        self.reset_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Reset</p></body></html>"))
        self.reset_button.setText(_translate("MainWindow", "..."))
        self.multistep_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Settings</p></body></html>"))
        self.multistep_button.setText(_translate("MainWindow", "..."))
        self.pause_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pause</p></body></html>"))
        self.pause_button.setText(_translate("MainWindow", "..."))
        self.canvas_label.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.mistake.setText(_translate("MainWindow", "&Just don\'t click here"))
        self.mistake.setToolTip(_translate("MainWindow", "Really, don\'t"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

